version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: docker/webapp.Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Database=well_euled;Username=postgres;Password=postgres
    depends_on:
      - db
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: well_euled
    volumes:
      - well_euled_data:/var/lib/postgresql/data
volumes:
  well_euled_data: