name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Build API Docker image
      - name: Build API Docker image
        run: docker build -f docker/api.Dockerfile -t well-euled-api .

      # Run API container
      - name: Run API container
        run: |
          docker run -d --name api \
            -e ASPNETCORE_URLS=http://+:5000 \
            -e DOTNET_USE_POLLING_FILE_WATCHER=1 \
            -p 5000:5000 well-euled-api
          # Wait for API to be ready
          for i in {1..30}; do
            if curl --fail http://localhost:5000/graphql; then
              echo "API is up!"
              break
            fi
            echo "Waiting for API..."
            sleep 2
          done

      # Install StrawberryShake as a local tool
      - name: Setup StrawberryShake local tool
        run: |
          cd src/BlazorApp/BlazorApp
          dotnet new tool-manifest || echo "Tool manifest already exists"
          dotnet tool install StrawberryShake.Tools --version 15.1.10 || echo "Tool already installed"

      # Generate StrawberryShake client
      - name: Generate StrawberryShake client
        run: |
          cd src/BlazorApp/BlazorApp
          dotnet graphql init http://localhost:5000/graphql -n WellEuledClient || echo "Already initialized"
          dotnet graphql update
          ls

      # Commit generated client
      - name: Commit generated GraphQL client
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add src/BlazorApp/BlazorApp/schema.extensions.graphql
          git add src/BlazorApp/BlazorApp/schema.graphql
          git add src/BlazorApp/BlazorApp/.graphqlrc.json
          git commit -m "Update StrawberryShake GraphQL client" || echo "No changes to commit"
          git push || echo "Push failed, likely due to no changes"
